## Numpy Tutorial

In [1]:
import numpy as np

np.random.randn(20)

array([-0.2437007 ,  0.20664325, -0.5526014 ,  0.09661953, -1.38473488,
        0.15775498, -0.57295656,  0.60728466,  0.32191915, -1.14687457,
       -1.0738633 ,  0.08957938,  1.7921492 ,  0.61082385,  0.48029965,
       -1.67994052,  0.08845947,  1.30556059,  0.36737336, -2.39534695])

In [3]:
a = np.ones(100)

In [4]:
a.reshape(2,2,5,5)

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [7]:
a = np.arange(20).reshape(5,4)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
b = np.array_split(a, 2)

In [23]:
b

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [32]:
a.size * a.itemsize

160

In [29]:
from sys import getsizeof
getsizeof(a)

112

In [28]:
a.nbytes

160