In [13]:
import torch
import numpy as np

In [18]:
x = np.random.randn(5,3)
x.shape

(5, 3)

In [17]:
x_ = torch.tensor(x)
x_.shape

torch.Size([5, 3])

In [19]:
x_.numpy()

array([[ 0.6506051 ,  1.88385952,  0.35856224],
       [-0.27210322, -0.50659936,  0.82393947],
       [ 1.35116637,  0.39116877, -1.54591428],
       [-0.98713706, -0.77116797, -2.05745983],
       [-0.89686842,  0.20980419, -0.0901276 ]])

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.3563e-19, 1.8888e+31, 8.9066e-15],
        [1.8888e+31, 6.4639e-04, 6.8608e+22],
        [1.7753e+28, 2.0535e-19, 7.5563e+31],
        [1.8014e+25, 8.1335e+32, 7.2436e+22],
        [7.5554e+28, 2.9635e+29, 2.2087e+03]])


In [24]:
x_.size()

torch.Size([5, 3])

In [4]:
a = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [26]:
b = torch.randn_like(x_, dtype=torch.float)    # override dtype!
print(x)    

[[-1.6964378   1.2825655   0.74060718]
 [ 1.0608011  -1.20885561 -0.70351241]
 [ 0.72542479 -1.26800784 -0.98929577]
 [-0.04374985  0.29025764 -1.50668209]
 [ 0.71048346 -1.94656853 -0.67913788]]


In [33]:
y = torch.rand_like(x_)
y

tensor([[0.8071, 0.8610, 0.9943],
        [0.3923, 0.6332, 0.2062],
        [0.3604, 0.6211, 0.2855],
        [0.1213, 0.4926, 0.6195],
        [0.7507, 0.7368, 0.1957]], dtype=torch.float64)

In [34]:
print(x_ + y)

tensor([[ 1.4577,  2.7449,  1.3529],
        [ 0.1202,  0.1266,  1.0301],
        [ 1.7115,  1.0123, -1.2604],
        [-0.8658, -0.2786, -1.4379],
        [-0.1462,  0.9466,  0.1055]], dtype=torch.float64)


In [35]:
np.add(x_, y)

tensor([[ 1.4577,  2.7449,  1.3529],
        [ 0.1202,  0.1266,  1.0301],
        [ 1.7115,  1.0123, -1.2604],
        [-0.8658, -0.2786, -1.4379],
        [-0.1462,  0.9466,  0.1055]], dtype=torch.float64)

In [36]:
# Any operation that mutates a tensor in-place is post-fixed with an _
y.add_(x_) #adds in placa

tensor([[ 1.4577,  2.7449,  1.3529],
        [ 0.1202,  0.1266,  1.0301],
        [ 1.7115,  1.0123, -1.2604],
        [-0.8658, -0.2786, -1.4379],
        [-0.1462,  0.9466,  0.1055]], dtype=torch.float64)

In [38]:
c = np.array([2,4,5])
d = torch.as_tensor(c)
c, d

(array([2, 4, 5]), tensor([2, 4, 5]))

In [39]:
# changing the value in array chenges the value in the tensor
c[0] = 4
c, d

(array([4, 4, 5]), tensor([4, 4, 5]))

In [40]:
# Resize/reshape 
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [46]:
a = np.arange(10).reshape(5,2)

In [45]:
a.squeeze().shape

(5, 2)

AutoGrad

In [47]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [49]:
d = x**2
d

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

In [53]:
print(d.grad_fn)

In [56]:
z = x * x * 3
out = z.mean()

print(z, out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward0>)


In [57]:
out.backward()

In [58]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [59]:
torch.cuda.is_available()

False